export const SERVICE_SUBTITLES: Record<string, string[]> = {
  "elektrik-ruhsat-projeleri": [
    "Mimari Tasarım Uyumluluk ve Ön Hazırlık",
    "Vaziyet Planı Üzerinde Enerji Giriş Noktası Belirlenmesi",
    "Yapı Sınıfı ve Kullanım Amacına Göre Yük Analizi",
    "Şaft, Kanal ve Galeri Geçiş Güzergahlarının Belirlenmesi",
    "Elektrik Odası ve Pano Alanlarının Mimari Koordinasyonu",
    "Islak Hacim ve Tehlikeli Mahallerin Teknik Sınırlandırmaları",
    "Kat Yükseklikleri ve Tavan Tipi Uygunluk Analizi",
    "Yangın Kompartıman Geçişlerinde Sızdırmazlık Kriterleri",
    "Dış Aydınlatma ve Çevre Düzenleme Entegrasyonu",
    "Engelli Erişimi ve Ergonomi Standartlarına Uygunluk",
    "Mekanik Tesisat (HVAC) Ekipman Listesi ve Güç İhtiyaçları",
    "Dilatasyon Geçiş Detayları ve Esnek Bağlantı Çözümleri",
    "Asansör Kuyusu ve Makine Dairesi Elektriksel Gereksinimleri",
    "Çatı Tipi ve Eğimine Göre Güneş Paneli Yerleşim Etüdü",
    "Temel Elektrik Hesaplamaları ve Raporlama",
    "Kurulu Güç ve Talep Gücü Hesaplama Yöntemleri",
    "Gerilim Düşümü ve İletken Kesit Mukavemet Analizleri",
    "Akım Taşıma Kapasitesi ve Çevresel Faktörlerin Etkisi",
    "Isıl Kararlılık ve Kısa Devre Dayanımı Hesapları",
    "Aydınlatma Seviyesi (Lux) ve Armatür Verimlilik Analizleri",
    "Harmonik Analizi ve Filtreleme Gereklilik Raporu",
    "Trafo Kayıpları ve Verimlilik Hesaplamaları",
    "Güneş Enerjisi (GES) Mahsuplaşma ve Bağlantı Fizibilitesi",
    "Kablo Isınma ve Boru Çapı Doluluk Oranı Hesapları",
    "Acil Durum Jeneratör Kapasite ve Devreye Girme Analizi",
    "Motor Kalkış Akımları ve Yumuşak Yol Verici (Soft Starter) Hesabı",
    "Reaktif Güç İhtiyacı ve Sabit Grup Kompanzasyon Belirleme",
    "Eşzamanlılık (Diversite) Faktörü ve Bölgesel Yük Dağılımı",
    "Ana Dağıtım ve Koruma Sistemleri Tasarımı",
    "Ana Dağıtım Panosu (ADP) Yerleşim ve Tek Hat Şemaları",
    "Selektivite ve Koruma Koordinasyonu (LSI, LSIG)",
    "Kompanzasyon Sistemi Tasarımı ve Reaktif Güç Kontrolü",
    "Kaçak Akım Koruma (RCD) Kademelendirme ve Seçicilik",
    "Darbe Gerilimi ve Parafudr (SPD) Koruma Sınıfları",
    "Şebeke - Jeneratör Transfer Sistemi ve Kilitleme Mantığı",
    "Ölçü Hücreleri ve Akım/Gerilim Trafosu Seçim Esasları",
    "Busbar Enerji Dağıtım Sistemleri ve Çıkış Kutusu Konfigürasyonu",
    "Pano İçi Termal Yönetim ve Havalandırma Sistemleri",
    "Akıllı Şebeke (Smart Grid) Uyumlu İzleme Modülleri",
    "IP ve IK Koruma Sınıflarının Ortam Şartlarına Göre Belirlenmesi",
    "Ark Hatası Algılama Cihazları (AFDD) Entegrasyonu",
    "Enerji Kalitesi Analizörü ve Uzaktan Sayaç Okuma (OSOS)",
    "Aydınlatma ve Priz Tesisat Planlaması",
    "Oda Bazlı Fonksiyonel Aydınlatma Tasarımı",
    "Güç Tesisatı ve Özel Endüstriyel Priz Grupları",
    "Acil Durum ve Kaçış Yolu Aydınlatma Armatürleri",
    "DALI ve KNX Tabanlı Aydınlatma Otomasyon Sistemleri",
    "Sensörlü Aydınlatma ve Enerji Tasarrufu Stratejileri",
    "Kesintisiz Güç Kaynağı (UPS) Beslemeli Kritik Priz Hatları",
    "Dış Cephe ve Mimari Vurgu Aydınlatması Detayları",
    "Zemin ve Masaüstü Veri/Enerji Dağıtım Kutuları",
    "Temizlik ve Servis Prizleri İçin Eşzamanlılık Katsayısı",
    "Ex-Proof Aydınlatma ve Patlayıcı Ortam Tesisat Esasları",
    "Mavi Işık Tehlikesi (UGR) ve Görsel Konfor Kriterleri",
    "Sirkadiyen Aydınlatma ve İnsan Odaklı Işık Tasarımı",
    "Dimleme (Karartma) Senaryoları ve Bölgesel Kontrol",
    "Topraklama ve Yıldırımdan Korunma Sistemleri",
    "Temel Topraklaması ve Betonarme Demir İletkenliği",
    "Potansiyel Dengeleme ve Eşpotansiyel Bara Bağlantıları",
    "Paratoner (E.S.E) Yarıçap Hesabı ve Risk Analizi",
    "Faraday Kafesi Tasarımı ve Mesh Sistemi Uygulamaları",
    "Koruma ve İşletme Topraklaması Ayrımı/Entegrasyonu",
    "Toprak Özgül Direnci Ölçümü ve Elektrot Konfigürasyonu",
    "Yıldırım İniş İletkenleri ve Test Klemens Noktaları",
    "Hassas Elektronik Cihazlar İçin Sinyal Topraklaması",
    "Statik Elektrik Deşarj (ESD) Önleme ve Topraklama",
    "Katodik Koruma Sistemleri ile Elektriksel Etkileşim",
    "Topraklama Yayılma Direnci Hesaplama Yazılımları",
    "Adım ve Dokunma Gerilimi Limitlerinin Kontrolü",
    "Kimyasal Topraklama Çubukları ve Direnç Düşürücü Tozlar",
    "Zayıf Akım ve İletişim Altyapısı",
    "Yapısal Kablolama ve Veri Merkezi (Data Center) Tasarımı",
    "IP Telefon ve Santral Sistemleri Projelendirme",
    "CCTV Kamera İzleme ve Kayıt Sistemleri Mimarisi",
    "Kartlı Geçiş ve Biyometrik Güvenlik Sistemleri",
    "Merkezi Uydu (TV-SAT) ve SMATV Dağıtım Şebekesi",
    "Hemşire Çağrı ve Acil Yardım İnterkom Sistemleri",
    "Profesyonel Seslendirme ve Acil Anons (PA/VA) Sistemleri",
    "Bina Otomasyon (BMS) ve Enerji Yönetim Yazılımları",
    "Akıllı Ev Teknolojileri ve Uzaktan Kontrol Protokolleri",
    "Fiber Optik (FTTH) Altyapı ve Omurga Dağıtımı",
    "Kablosuz Erişim Noktası (Wi-Fi) Isı Haritası ve Planlama",
    "Otopark Doluluk ve Yönlendirme Sistemleri Entegrasyonu",
    "Merkezi Saat Sistemleri ve Senkronizasyon Altyapısı",
    "Orta Gerilim (OG) ve Trafo Merkezi Tasarımı",
    "OG Hücre Tipleri (Giriş-Çıkış, Ölçü, Kesici) Seçimi",
    "Trafo Güç Hesabı ve Yağlı/Kuru Tip Tercih Kriterleri",
    "OG Kablo Kesit Hesabı ve Ek Müfrezeleri",
    "Koruma Röleleri (Aşırı Akım, Toprak, Diferansiyel) Ayarları",
    "Trafo Merkezi Havalandırma ve Gazlı Söndürme Entegrasyonu",
    "Beton Köşk ve Hücre Yerleşim Planları",
    "OG Topraklama Ağı ve Şalt Sahası Emniyet Tedbirleri",
    "Manevra Senaryoları ve Tek Hat Kilitleme Diyagramları",
    "Reaktif Güç Ölçüm Noktaları ve OG Kompanzasyon",
    "Geçici Kabul ve İşletme Sorumluluğu Dosya Hazırlığı",
    "Kesintisiz Güç Kaynağı (UPS) ve Yedekleme Sistemleri",
    "UPS Güç Kapasite Hesabı ve Akü Grubu Seçimi",
    "Dinamik ve Statik UPS Teknolojileri Karşılaştırması",
    "Kritik Yük Dağıtım Panoları ve Bypass Devreleri",
    "UPS Odası Havalandırma ve İklimlendirme Kriterleri",
    "Akü İzleme Sistemleri (BMS) ve Ömür Analizi",
    "Harmonik Filtreleme ve Giriş/Çıkış İzolasyon Trafoları",
    "Paralel ve Yedekli (N+1) UPS Konfigürasyonları",
    "Veri Merkezleri İçin Tier Standartlarına Uygun Yedekleme",
    "Voltaj Regülatörleri ve Şebeke İyileştirme Çözümleri",
    "Uzaktan İzleme ve SNMP Tabanlı Yönetim Altyapısı",
    "Yenilenebilir Enerji (GES) ve Şebeke Entegrasyonu",
    "Çatı Tipi GES İçin Statik Yük ve Alan Analizi",
    "İnverter (Evirici) Seçimi ve Verimlilik Eğrileri",
    "Çift Yönlü Sayaç ve Mahsuplaşma Teknik Dosyası",
    "Panel Dizilim (String) Planları ve Gölgeleme Analizi",
    "DC Koruma Kutuları ve Sigorta/Parafudr Seçimi",
    "Enerji Depolama Sistemleri (ESS) ve Hibrit Çözümler",
    "Şebekeye Geri Besleme (Feedback) ve Güvenlik Röleleri",
    "PV Kablolama Standartları ve UV Dayanımı Kriterleri",
    "Uzaktan İzleme (Scada) ve Üretim Raporlama Yazılımları",
    "Yıldırımdan Korunma ve GES Topraklama Spesifikasyonları",
    "Enerji Verimliliği ve Bina Otomasyonu (BMS)",
    "Aydınlatma ve HVAC Kontrol Senaryoları",
    "Enerji Sayaçları Üzerinden Bölgesel Tüketim Analizi",
    "VAV, Fan Coil ve Pompa Kontrol Modülleri",
    "Varlık (Presence) ve Gün Işığı Sensör Entegrasyonu",
    "KNX, BACnet ve Modbus Protokol Dönüştürücüleri",
    "Merkezi İzleme Yazılımı (SCADA) Grafik Arayüz Tasarımı",
    "Reaktif Enerji ve Talep Kontrol Otomasyonu",
    "Isı Pay Ölçer ve Elektrik Faturalandırma Yazılımları",
    "Akıllı Priz ve Cihaz Bazlı Enerji İzleme",
    "Otomasyon Panosu Tasarımı ve Saha Kablolaması",
    "Yangın Güvenliği ve Acil Durum Yönetimi (Elektriksel)",
    "Yangına Dayanıklı (FE 180) Kablo Kullanım Alanları",
    "Acil Durum Anons ve Seslendirme Sistemi Bölgelemesi",
    "Duman Tahliye Fanları Güç ve Kumanda Panoları",
    "Yangın Damperleri Kontrol ve İzleme Modülleri",
    "Acil Aydınlatma Kiti Uygulamaları ve Batarya Testleri",
    "Kaçış Yolu Yönlendirme Tabelaları Lümen Değerleri",
    "Yangın Pompası Besleme ve Yıldız-Üçgen Kumanda Panoları",
    "Gaz Algılama ve Otomatik Kesici Vana Entegrasyonu",
    "Yangın Durumunda Enerji Kesme (Trip) Senaryoları",
    "Asansör Yangın Modu ve Kuyu Duman Tahliye Kontrolü",
    "Çevresel Şartlar ve Özel Alan Tesisatları",
    "Nemli ve Tozlu Alanlar İçin IP65/67 Tesisat Esasları",
    "Patlayıcı Ortamlar (ATEX) ve Ex-Proof Ekipman Seçimi",
    "Soğuk Hava Depoları ve Donma Karşıtı Isıtma Kabloları",
    "Kimyasal Laboratuvarlar İçin Korozyon Dayanımlı Kanallar",
    "Temiz Odalar (Clean Room) İçin Antimikrobiyal Anahtar/Prizler",
    "Havuz ve Islak Hacimler İçin Bölge (Zone) Sınıflandırması",
    "Hastane Ameliyathane ve Yoğun Bakım İzole Güç Sistemleri",
    "Otopark Kar Erime ve Çatı Dere Isıtma Sistemleri",
    "Deniz Kenarı Tesislerde Tuzlu Su Korozyon Koruması",
    "Yüksek Radyasyonlu Alanlar İçin Elektriksel İzolasyon",
    "İş Güvenliği ve Teknik Denetim Standartları",
    "LOTO (Kilitleme/Etiketleme) Güvenlik Prosedürleri",
    "Pano İçi Koruyucu Bariyerler ve Pleksiglas Korumalar",
    "Ark Flaş (Arc Flash) Analizi ve Kişisel Koruyucu Donanım",
    "Elektrik Odası Kauçuk Paspas ve Uyarı Levhaları",
    "Topraklama ve Süreklilik Ölçüm Raporlama Formatları",
    "Termal Kamera İle Pano Sıcaklık Kontrol Metotları",
    "Kaçak Akım Rölesi Fonksiyonel Test Raporları",
    "İşletme Bakım ve Onarım Talimatnameleri Hazırlığı",
    "Periyodik Kontrol Takvimi ve Teknik Envanter Yönetimi",
    "Acil Durum Müdahale Planı ve Elektriksel Şemalar",
    "Proje Yönetimi ve Onay Süreçleri",
    "Belediye ve OSB Teknik Şartname Uygunluk Kontrolü",
    "Dağıtım Şirketi (UEDAŞ vb.) Enerji Müsaadesi Takibi",
    "Proje Tasarım Aşamaları (Avan, Uygulama, Detay)",
    "BIM (Building Information Modeling) ve Revit Entegrasyonu",
    "Teknik Metraj ve Keşif Özeti Hazırlama Yöntemleri",
    "Şartname Hazırlama ve Malzeme Onay Formları (MAR)",
    "Geçici Kabul ve Kesin Kabul Elektriksel Eksik Listesi",
    "As-Built (Son Durum) Projelerinin Sahada Doğrulanması",
    "Enerji Kimlik Belgesi (EKB) İçin Elektriksel Veri Girişi",
    "Proje Arşivleme ve Versiyon Kontrol Sistemleri",
    "Enerji Kalitesi ve Harmonik Yönetimi",
    "Toplam Harmonik Distorsiyon (THDv/THDi) Limitleri",
    "Pasif ve Aktif Harmonik Filtre Tasarımı",
    "Nötr Hattı Isınma Analizi ve Kesit Artırımı Gerekçeleri",
    "Ani Gerilim Sıçramaları (Sag/Swell) ve Kayıt Analizi",
    "Flicker (Gerilim Kırpışması) Analizi ve Çözümleri",
    "Güç Faktörü (Cos φ) İyileştirme ve Reaktif Ceza Önleme",
    "Enerji Kalitesi Analizörü Bağlantı Noktaları ve Raporlama",
    "Hassas Veri İşleme Merkezleri İçin Temiz Toprak ve Güç",
    "K-Faktörü Trafolar ve Harmonik Dayanımlı Ekipmanlar",
    "Akıllı Şebeke (Smart Grid) İzleme ve Veri Analitiği"
  ],
  "elektrik-uygulama-projeleri": [
    "Dağıtım Sistemleri ve Enerji İletim Hatları",
    "Ana Dağıtım ve Tali Pano Besleme Hatları Tasarımı",
    "Kablo Kanalı, Merdiven ve Busbar Güzergah Planlaması",
    "Yeraltı Kablo Galerileri ve Borulama Sistemleri Detayları",
    "Kablo Taşıyıcı Doluluk Oranı ve Isınma Etkisi Analizi",
    "Dikey Şaft Geçişleri ve Katlar Arası Enerji Dağıtımı",
    "Branşman ve Ek kutusu (Tap-off) Yerleşim Kriterleri",
    "Halojensiz (HFFR) Kablo Kullanım ve Montaj Standartları",
    "Kablo Gerilme Kuvveti ve Bükülme Yarıçapı Hesapları",
    "Yangın Durdurucu (Fire-Stop) Malzeme Uygulama Detayları",
    "Mekanik Darbelere Karşı Kablo Koruma ve Zırhlı Kablo Tercihi",
    "Kablo Etiketleme, Kodlama ve Renk Standartları (IEC 60446)",
    "Geçici Şantiye Elektriği ve Mobil Dağıtım Üniteleri",
    "Aydınlatma Tesisatı Uygulama Detayları",
    "İç Mekan Fonksiyonel ve Mimari Aydınlatma Yerleşimi",
    "Asma Tavan Tiplerine Göre Armatür Montaj Detayları",
    "Endüstriyel Yüksek Tavan (High-Bay) Aydınlatma Askı Sistemleri",
    "Acil Durum Aydınlatma ve Yönlendirme Armatür Kablajı",
    "Aydınlatma Kontrolü: Komütatör, Vavien ve Darbe Akımlı Röleler",
    "Dış Cephe (Facade) ve Peyzaj Aydınlatma Tesisatı",
    "Nemli Yer (Etanj) Armatür ve Tesisat Uygulama Kuralları",
    "Aydınlatma Sorti ve Linyelerinin Pano Bağlantı Şemaları",
    "Dimlenebilir (0-10V, DALI) Aydınlatma Altyapı Hazırlığı",
    "Sabit ve Hareketli (Ray Tipi) Aydınlatma Sistemleri",
    "Işıklık ve Galeri Boşluğu Aydınlatma Erişilebilirlik Analizi",
    "UV ve Hijyenik Aydınlatma (Laboratuvar/Hastane) Montajı",
    "Kuvvetli Akım Priz ve Güç Tesisatı",
    "Genel Kullanım ve Özel Fonksiyonlu Priz Yerleşimleri",
    "Endüstriyel Tip (Cee Norm) Kombinasyon Kutuları ve Montajı",
    "UPS Beslemeli Kritik Priz Hatları ve Renk Kodlaması",
    "Zemin Altı (Döşeme İçi) Kanal ve Buat Sistemleri",
    "Tezgah Üstü ve Ofis Mobilyası Enerji Dağıtım Modülleri",
    "Mutfak ve Islak Hacim Prizleri İçin IP Koruma Kriterleri",
    "Priz Sorti Hatlarında Kablo Kesit ve Sigorta Uyumu",
    "Veri Merkezi ve Server Odası Güç Dağıtım Üniteleri (PDU)",
    "Elektrikli Araç Şarj İstasyonu (EV) Altyapısı ve Kablolama",
    "Kablo Kanallarında Veri ve Enerji Hattı Ayrımı (Seperatör)",
    "Priz Linyelerinde Kaçak Akım Rölesi Koruması ve Testi",
    "Elektrik Panoları İmalat ve Montaj Standartları",
    "Pano Karkas Yapısı, Sac Kalınlığı ve Boya Spesifikasyonları",
    "Bara İşleme, Bükme ve İzolasyon Mesafesi Kriterleri",
    "Pano İçi Kablo Düzenleme, Kanallama ve Formlama (Form 1-4)",
    "Şalt Ekipman (Kilitli Şalter, Kontaktör, Röle) Montaj Düzeni",
    "Pano Klemens Dizilimi ve Giriş-Çıkış Kablo Bağlantı Detayları",
    "Havalandırma Fanı, Filtre ve Termostat Kontrollü Soğutma",
    "Pano İçi Isıtıcılar ve Nem Kontrolü (Yoğuşma Önleme)",
    "Kapı Üzeri Ölçü Aletleri, Sinyal Lambaları ve Etiketleme",
    "Ana Dağıtım Panolarında Bakır Bara ve Esnek Bağlantılar",
    "Pano Topraklama Barası ve Gövde Topraklama Sürekliliği",
    "Pano İçi Şematik Cep ve Güncel Tek Hat Şeması Bulundurma",
    "Tip Testli (IEC 61439-1/2) Pano Tasarımı ve Onay Süreci",
    "Motor Besleme ve Kumanda Sistemleri",
    "Mekanik Cihaz (Pompa, Fan, Klima Santrali) Güç Bağlantıları",
    "Yıldız-Üçgen (Y/D) ve Doğrudan (DOL) Kalkışlı Kumanda Devreleri",
    "Frekans Konvertörü (VFD) ve Yumuşak Yol Verici (Soft Starter) Panoları",
    "Motor Koruma Şalterleri ve Termik Röle Ayar Sahaları",
    "Uzaktan Durdurma (Acil Stop) Butonları ve Güvenlik Zinciri",
    "Motor Besleme Kablolarında Ekranlı (Shielded) Kablo Kullanımı",
    "Limit Switch ve Sensör Kablajı Uygulama Detayları",
    "MCC (Motor Control Center) Panoları ve Çekmeceli Üniteler",
    "Fan ve Pompa Otomasyonu (Senaryolu Çalışma) Altyapısı",
    "Elektrikli Motor Sürücüleri İçin Harmonik Filtre Uygulaması",
    "Topraklama ve Eşpotansiyel Sistem Uygulaması",
    "Temel Topraklaması ve İnşaat Demiri Bağlantı Noktaları",
    "Koruma Topraklaması ve Tali Pano Topraklama İnişleri",
    "Eşpotansiyel Kuşaklama ve Ana Topraklama Barası (MET)",
    "Banyo ve Islak Hacim Yerel Eşpotansiyel Bağlantıları",
    "Makine ve Ekipman Gövde Topraklama Metotları",
    "Bilgi İşlem (IT) Sistemleri İçin İzole Topraklama Barası",
    "Topraklama Prizleri ve Ölçüm Rögarı (Logar) Detayları",
    "Statik Elektrik Alıcıları ve ESD Yer Döşemesi Topraklaması",
    "Kablo Taşıyıcı Sistemlerin (Kanal/Merdiven) Topraklanması",
    "Topraklama İletkeni Ek ve Bağlantı Elemanları (Cadweld vb.)",
    "Yıldırımdan Korunma ve Parafudr Sistemleri",
    "Aktif Paratoner (ESE) Başlığı ve Direk Montaj Detayları",
    "İndirme İletkenleri (Bakır/Galvaniz) ve Koruma Borusu",
    "Yıldırım Sayıcı ve Test Klemensi Uygulama Noktaları",
    "Faraday Kafesi Çatı Üstü İletken ve Yakalama Çubuğu Dizaynı",
    "Tip 1, Tip 2 ve Tip 3 Parafudrların Pano İçi Entegrasyonu",
    "Güneş Panelleri ve Antenler İçin İzoleli Yıldırımlık İnişleri",
    "Dış Cephe Metal Kaplamaların Yıldırımlık Sistemine Dahil Edilmesi",
    "Adım Gerilimine Karşı Toprak Altı İletken Serilme Detayları",
    "Zayıf Akım Sistemleri Saha Uygulamaları",
    "Data/Telefon Prizi Montajı ve Kablo Sonlandırma (Keystone)",
    "Rack Kabinet Montajı, Patch Panel ve Switch Yerleşimi",
    "Yangın Algılama Dedektör, Buton ve Siren Montaj Detayları",
    "CCTV Kamera Ayak Montajı ve Buat İçi Kablo Bağlantıları",
    "Kartlı Geçiş Sistemi (Turnike, Manyetik Kilit) Uygulamaları",
    "Merkezi Seslendirme Hoparlör Trafo ve Hat Bağlantıları",
    "TV/Uydu Prizi ve Multiswitch Dağıtım Ünitesi Tesisatı",
    "İnterkom (Diafon) Şube ve Panel Montaj Kriterleri",
    "Bina Otomasyon (BMS) Saha Elemanları (DDC) Kablajı",
    "Güç Kaynakları ve Yedekleme Üniteleri (UPS/Jeneratör)",
    "Jeneratör Güç Bağlantısı ve Egzoz/Havalandırma Detayları",
    "Şebeke-Jeneratör Transfer Panosu (ATS) Montajı",
    "UPS Akü Grubu Yerleşimi ve Rack Tipi Akü Rafları",
    "Kesintisiz Güç Kaynağı Bypass ve Giriş-Çıkış Panoları",
    "Yakıt Besleme Sistemi ve Acil Durum Yakıt Kesme Valfi",
    "Jeneratör Senkronizasyon Panoları ve Yük Paylaşımı",
    "Orta Gerilim (OG) ve Trafo Merkezi Uygulamaları",
    "Modüler OG Hücrelerin Kaide Üstü Montajı ve Hizalanması",
    "Trafo Tekerlek Kilitleri ve Yağ Toplama Çukuru Detayları",
    "OG XLPE Kablo Başlığı Yapımı ve Koruma Rölesi Testleri",
    "Trafo Merkezi Havalandırma Menfezleri ve Fan Kontrolü",
    "OG Manevra Çubuğu, Eldiven ve Tabure Gibi Emniyet Ekipmanları",
    "Ayırıcı ve Kesici Mekanizmaları Yağlama ve Kontrolü",
    "Enerji Yönetimi ve İzleme Sistemleri",
    "Dijital Multimetre ve Enerji Analizörü Pano Montajı",
    "Akım Trafoları (CT) Seçimi ve Polarite Bağlantı Kontrolü",
    "Haberleşme (RS485/Ethernet) Hatları ve Gateway Cihazları",
    "Uzaktan Sayaç Okuma (OSOS) ve Faturalandırma Altyapısı",
    "Enerji İzleme Yazılımı İçin Veri Toplama Noktaları",
    "Özel Tesisatlar ve Teknolojik Sistemler",
    "Laboratuvar ve Hastane Tipi İzole Güç Sistemleri (IT)",
    "Ex-Proof (Atex) Ekipman ve Tesisat Uygulama Teknikleri",
    "Asansör ve Yürüyen Merdiven Besleme/Kumanda Detayları",
    "Isı İzleme (Heat Tracing) Kablo Uygulama ve Kontrolü",
    "Pnömatik Tüp Taşıma Sistemi Elektriksel Altyapısı",
    "Kablo Taşıyıcı ve Destek Sistemleri",
    "Tavana Askı (Rod/C Profil) ve Duvara Konsol Montajı",
    "Kablo Kanalları Dönüş, Ekleme ve Seviye Değişim Elemanları",
    "Tel Kanal Uygulamaları ve Veri Kablosu Destekleri",
    "Taşıyıcı Sistemlerde Genleşme (Dilatasyon) Geçişleri",
    "Ağır Hizmet Tipi Merdiven Kanalların Montaj Kriterleri",
    "Saha Testleri, Devreye Alma ve Kabul İşlemleri",
    "Kablo İzolasyon Direnci (Meğer) Ölçüm ve Raporlama",
    "Topraklama Direnci (Megger) Ölçüm Teknikleri",
    "Aydınlatma Seviyesi (Lüksmetre) Ölçümü ve Doğrulama",
    "Kaçak Akım Rölesi (RCD) Açma Zamanı ve Akımı Testleri",
    "Şalt Ekipman Termografik (Isıl) Muayene Analizi",
    "Sistem Sürekliliği ve Fonksiyonel Senaryo Denemeleri",
    "Teknik Dökümantasyon ve İşletme Teslimi",
    "Sahadaki Değişikliklerin İşlendiği Kırmızı Hatlı (Red-Line) Çizimler",
    "As-Built (Son Durum) Projelerinin Hazırlanması ve Onayı",
    "İşletme ve Bakım El Kitaplarının (O&M) Oluşturulması",
    "Teknik Eğitimlerin Verilmesi ve Devir Teslim Tutanağı",
    "Garanti Takip Sistemi ve Yedek Parça Listeleri"
  ],
  "elektrik-abone-projeleri": [
    "Abonelik Türleri ve Başvuru Sınıflandırması",
    "Mesken (Konut) Grubu Abonelik Projeleri Kriterleri",
    "Ticarethane ve Sanayi Grubu Abonelik Farklılıkları",
    "Tarımsal Sulama ve Hayvancılık Tesisleri Abonelik Esasları",
    "Şantiye (Geçici) Elektriği Abonelik Süreçleri",
    "Genel Aydınlatma ve Ortak Alan Abonelik Planlaması",
    "İbadethane ve Vakıf Muafiyetli Abonelik Dosyaları",
    "Geçici Etkinlik (Fuar, Konser) Kısa Süreli Abonelikleri",
    "Sosyal Yardımlaşma Kapsamında İndirimli Abonelik Teknikleri",
    "Dağıtım Şirketi Teknik Dosya Hazırlığı",
    "Enerji Müsaadesi (Bağlantı Görüşü) Başvuru Formları",
    "Tapu, Yapı Ruhsatı ve Kimlik Bilgilerinin Dosya Entegrasyonu",
    "Onaylı Elektrik Ruhsat Projesinin Abone Dosyasına Uyarlanması",
    "Tek Hat Şeması ve Yük Tablosunun Güncel Durum Analizi",
    "Tesisat Numarası ve Lokalizasyon (Adres) Doğrulaması",
    "Yetkili Elektrikçi Sicil ve İmza Sirküleri Dökümantasyonu",
    "Sayaç Panosu Tasarım ve Yerleşim Detayları",
    "Çoklu Abone (Kolektif) Sayaç Panosu Mimari Yerleşimi",
    "Münferit (Bireysel) Sayaç Panosu IP Koruma Sınıfları",
    "Sayaç Panosu Kilitleme ve Mühürleme Düzenekleri",
    "Pano İçi Isınma ve Havalandırma Menfezi Standartları",
    "Sayaç Panosu Yüksekliği ve Okuma Kolaylığı Kriterleri",
    "Acil Durumda Sayaç Panosuna Erişim ve Güvenlik Protokolleri",
    "Ölçü Sistemleri ve Sayaç Seçim Esasları",
    "Aktif, Reaktif ve Kapasitif Ölçüm Yapabilen Elektronik Sayaçlar",
    "Doğrudan Bağlantılı (Direkt) Sayaç Seçim Akım Limitleri",
    "Akım Trafolu (X/5) Ölçü Devreleri ve Bağlantı Şemaları",
    "Gerilim Trafolu (OG) Ölçüm Sistemleri ve Hücre Tasarımı",
    "Akıllı Sayaç (AMR/AMI) Teknolojileri ve Uzaktan Okuma",
    "Sayaç Hassasiyet Sınıfları (Class 0.5, 1, 2) ve Kalibrasyon",
    "Branşman Hattı ve Kofre Bağlantı Noktaları",
    "Ana Besleme Hattı (Hava/Yeraltı) Kablo Kesit Analizi",
    "Kofre (Ana Sigorta) Kutusu Seçimi ve Selektivite Uyumu",
    "Cephe Branşman Direği ve Konsol Montaj Detayları",
    "Yeraltı Branşman Kablosu Koruma Borusu ve Rögar Geçişleri",
    "Mevcut Şebekeye En Yakın Bağlantı Noktası (A-B Noktası) Etüdü",
    "Gerilim Düşümü ve Akım Taşıma Kapasitesi Limit Kontrolü",
    "Reaktif Güç ve Kompanzasyon Uyumluluğu",
    "Reaktif Enerji Tarifesi ve Ceza Sınırları Analizi",
    "Münferit ve Merkezi Kompanzasyon Sistemi Seçimi",
    "Harmonik Filtreli Kompanzasyon Gereklilik Raporu",
    "Reaktif Güç Kontrol Rölesi Ayarları ve Haberleşme",
    "Akım Trafosu Seçimi ve Ölçü Devresi Polarite Testi",
    "Topraklama ve Koruma Elemanları Denetimi",
    "İşletme ve Koruma Topraklaması Ölçüm Raporları",
    "Ana Giriş Kaçak Akım Koruma (300mA) Seçiciliği",
    "Potansiyel Dengeleme Barası ve Sayaç Panosu Bağlantısı",
    "Topraklama Direnci Sınır Değerleri ve Teknik İyileştirmeler",
    "Güç Artırımı ve İlave Abonelik Talepleri",
    "Mevcut Kurulu Güç Analizi ve Ek Kapasite İhtiyacı",
    "Trafo ve Ana Pano Revizyon Gereksinimleri",
    "Abonelik Devri ve İsim Değişikliği Teknik İncelemesi",
    "Şantiye Elektriği ve Geçici Tesisat",
    "İnşaat Sahası Geçici Pano ve Aydınlatma Planı",
    "Şantiye Süresi ve Uzatma Talebi Prosedürleri",
    "İş Güvenliği Standartlarına Uygun Geçici Dağıtım",
    "Dağıtım Şirketi Saha Kontrolü ve Mühürleme",
    "Tesisatın Onaylı Projeye Uygunluk Denetimi",
    "Sigorta ve Şalter Akım Değerleri Doğrulaması",
    "Mühürleme Öncesi Kablaj ve Bağlantı Sıkılık Kontrolü",
    "Kurumsal ve Endüstriyel Abonelik Yönetimi",
    "Fabrika ve OSB İçi Abonelik Ayrıştırma (Sub-metering)",
    "Yüksek Gerilim (YG) Müşteri Sınıfı Abonelik Kriterleri",
    "Enerji Tedarik Şirketi Seçimi ve Teknik Geçiş Dosyası",
    "Hukuki ve Mevzuat Uyumluluğu",
    "EPDK Elektrik Piyasası Müşteri Hizmetleri Yönetmeliği",
    "Usulsüz ve Kaçak Elektrik Kullanımı Teknik Önlemleri",
    "Tüketici Hakları ve Enerji Kesme/Açma Protokolleri",
    "Enerji Kalitesi ve Sayaç Arızaları",
    "Sayaç Arıza Tespiti ve Değişim Prosedürü",
    "Gerilim Dalgalanmalarının Ölçüm Hassasiyetine Etkisi",
    "Sayaç İleri/Geri Kayıt Analizi ve İtiraz Süreçleri",
    "Otomasyon ve Uzaktan Yönetim (Smart Grid)",
    "OSOS (Otomatik Sayaç Okuma Sistemi) Kurulum Esasları",
    "GPRS/GSM Modem ve Anten Yerleşim Detayları",
    "Veri Güvenliği ve Sayaç Verilerinin Şifrelenmesi",
    "Kabul, Onay ve Enerji Verme",
    "Nihai Bağlantı Anlaşması ve Sözleşme Gücü Belirleme",
    "Geçici Kabul Tutanağı ve Enerji Verme Onayı",
    "İlk Enerji Verme Sırasında Sistem Testleri ve Güvenlik"
  ],
  "elektrik-guc-arttirimi-projeleri": [
    "Mevcut Durum Analizi ve Kapasite Ekspertizi",
    "Mevcut Kurulu Güç ve Sözleşme Gücü Değerlendirmesi",
    "Fiili Yük Ölçümü ve Maksimum Demant Analizi",
    "Mevcut Ana Besleme Kablosu Kesit ve Isınma Kontrolü",
    "Mevcut Trafo Kapasitesi ve Rezerv Güç Oranı Tespiti",
    "Mevcut Şalt Ekipmanlarının (Şalter, Sigorta) Termal Analizi",
    "Sistemdeki Gerilim Düşümü Sorunlarının Sahada Tespiti",
    "Mevcut Kompanzasyon Sisteminin Verimlilik Etüdü",
    "Altyapı Yaşlanma Faktörü ve Yenileme İhtiyacı Raporu",
    "İlave Yük Hesapları ve Projelendirme Kriterleri",
    "Yeni Eklenecek Makine Parkuru ve Ekipman Listesi Analizi",
    "Yeni Kurulu Güç ve Talep Gücü (Eşzamanlılık) Hesapları",
    "Toplam Güç Artışı Oranına Göre Enerji Müsaadesi Stratejisi",
    "İlave Yüklerin Faz Dengesi (Balans) Üzerindeki Etkisi",
    "Motor Kalkış Akımları İçin Dinamik Gerilim Düşümü Hesabı",
    "Kısa Devre Akımı Artış Analizi ve Ekipman Dayanımı",
    "Ana Dağıtım Panosu (ADP) ve Şalt Revizyonu",
    "Ana Şalter (Giriş Şalteri) Kapasite Artışı ve Değişimi",
    "Pano Baralarının Akım Taşıma Kapasitesinin Güçlendirilmesi",
    "İlave Çıkış Şalterleri İçin Pano İçi Yerleşim (Layout) Revizyonu",
    "Pano İçi Havalandırma ve Soğutma Kapasitesinin Artırılması",
    "Selektivite Koordinasyonunun Yeni Güç Seviyesine Göre Güncellenmesi",
    "Eski Tip Sigortaların Yeni Nesil Kompakt Şalterler (MCCB) ile Değişimi",
    "Enerji Besleme Hattı (Branşman) Güçlendirme",
    "Mevcut Kabloya Paralel Kablo Çekilmesi vs. Kablo Değişimi Analizi",
    "Yeraltı Kablo Kanalları ve Boru Çapı Uygunluk Denetimi",
    "Kablo Başlıkları ve Ek Müfrezelerinin Yenilenmesi",
    "Mesafe Bazlı Gerilim Düşümü İyileştirme Metotları",
    "Hava Hattı Branşmanlarında İletken ve İzolatör Revizyonu",
    "Trafo Merkezi ve OG Hücre Güncellemeleri",
    "Trafo Değişimi (Örn: 400 kVA'dan 1000 kVA'ya Geçiş) Prosedürleri",
    "OG Hücrelerindeki Akım Trafoları ve Koruma Rölesi Ayarları",
    "Trafo Köşkü Havalandırma ve Emniyet Mesafesi Revizyonları",
    "Trafo Alçak Gerilim (AG) Çıkış Baralarının Modifikasyonu",
    "OG Kablo Kesitlerinin Kapasite Artışına Uygunluk Kontrolü",
    "Kompanzasyon Sistemi Kapasite Artırımı",
    "Artan Endüktif Yüke Göre Yeni Kondansatör Grubu Hesabı",
    "Reaktif Güç Kontrol Rölesi Kademe Sayısının Artırılması",
    "Harmonik Filtreli Kompanzasyon Ünitelerinin Eklenmesi",
    "Kompanzasyon Besleme Kablosu ve Kontaktör Revizyonu",
    "Jeneratör ve UPS Sistemi Entegrasyonu",
    "Artan Kritik Yüklere Göre Jeneratör Kapasite Analizi",
    "Transfer Panosu (ATS) Şalterlerinin Büyütülmesi",
    "UPS Akü Grupları ve Besleme Hatlarının Güncellenmesi",
    "Yedek Güç Senaryolarının (Load Shedding) Yeniden Yapılandırılması",
    "Bina Otomasyonu ve Enerji İzleme (SCADA) Revizyonu",
    "Yeni Eklenen Enerji Analizörlerinin Sisteme Entegrasyonu",
    "Talep Kontrol (Peak Shaving) Yazılım Ayarlarının Güncellenmesi",
    "Uzaktan İzleme Noktalarının ve Gateway Cihazlarının Artırılması",
    "Topraklama ve Yıldırımdan Korunma Güncellemeleri",
    "Artan Trafo Gücüne Göre İşletme Topraklaması Revizyonu",
    "Yeni Eklenen Ekipmanlar İçin Eşpotansiyel Bara Bağlantıları",
    "Yeni Tesis Alanları İçin Yıldırımdan Korunma Risk Analizi",
    "Dağıtım Şirketi (UEDAŞ/OSB) Onay Süreçleri",
    "Güç Artırımı Dosyası Hazırlama ve Başvuru Kriterleri",
    "Enerji Bağlantı Anlaşması ve Ek Sözleşme Prosedürleri",
    "Saha Kontrolü, Mühürleme ve Enerji Verme Protokolleri",
    "Enerji Verimliliği ve Kayıp-Kaçak Analizi",
    "Güç Artışı Sonrası Trafo Verimlilik Eğrisi Analizi",
    "İletken Kayıplarının (Joule Kaybı) Ekonomik Analizi",
    "Enerji Kimlik Belgesi (EKB) Güncelleme Gereksinimleri",
    "Endüstriyel Tesislerde Makine Bazlı Güç Dağıtımı",
    "CNC, Robotik Hatlar ve Yüksek Güçlü Motorların Beslemesi",
    "Busbar Çıkış Kutularının (Tap-off) Kapasite ve Tip Seçimi",
    "Harmonik Üreten Cihazlar İçin Özel Filtreleme Uygulamaları",
    "İş Güvenliği ve Teknik Denetim (LOTO)",
    "Güç Artırımı Çalışmaları Sırasında Enerji Kesme Planı",
    "Yeni Şalt Ekipmanları İçin Kilitleme ve Etiketleme (LOTO)",
    "Ark Flaş Analizi ve Yeni Koruma Ayarlarının Onayı",
    "Teknik Metraj, Keşif ve Maliyet Analizi",
    "Güç Artırımı İşi İçin Malzeme ve İşçilik Keşif Özeti",
    "Yatırımın Geri Dönüş Süresi (ROI) ve Enerji Tasarrufu Analizi",
    "Revizyon Sırasındaki Üretim Kaybı ve Risk Değerlendirmesi",
    "Kabul, Test ve As-Built Süreçleri",
    "Revizyon Sonrası İzolasyon ve Topraklama Testleri",
    "Yeni Şemaların As-Built Proje Olarak Sisteme İşlenmesi",
    "Nihai Enerji Kabulü ve Tesisin Teslim Edilmesi"
  ],
  "fabrika-as-built-revizyon-projeleri": [
    "Mevcut Tesis Röleve ve Saha Tespit Çalışmaları",
    "Mevcut Elektrik Panolarının Konum ve Fiziksel Durum Tespiti",
    "Kablo Tavaları, Busbar ve Boru Hatlarının Fiili Rotalarının Çıkarılması",
    "Saha Elemanlarının (Armatür, Priz, Sensör) Güncel Adet ve Yer Kontrolü",
    "Gizli Tesisat ve Yeraltı Hattı Tespiti İçin Teknik Yöntemler",
    "Makine Besleme Noktalarının Koordinatlı İşaretlenmesi",
    "Elektrik Odaları ve Şaftların Mevcut Mimari Uyum Kontrolü",
    "Pano İçi Revizyon ve Şema Doğrulama",
    "Mevcut Tek Hat Şemalarının Sahadaki Kablaj ile Karşılaştırılması",
    "Pano İçi Şalt Malzeme Marka, Model ve Kapasite Envanteri",
    "Boşta Kalan (İptal Edilen) Kabloların Tespiti ve Temizlenmesi",
    "Klemens Dizilimi ve Kablo Etiketlerinin Güncellenmesi",
    "Pano İçi Isınma ve Mekanik Deformasyon Analizi (Termal Gözlem)",
    "Yedek Şalter (Spare) Kapasitesinin ve Kullanılabilirliğinin Tespiti",
    "Kablo ve İletken Sistemleri Güncellemesi",
    "Mevcut Kablo Kesitlerinin Akım Taşıma ve Gerilim Düşümü Tahkiki",
    "Yıllanmış Kabloların İzolasyon Direnci (Meğer) Testleri",
    "Kablo Taşıyıcı Sistemlerin Mekanik Yük ve Doluluk Analizi",
    "Busbar Sistemlerinde Ek Noktaları ve Çıkış Kutusu Kontrolleri",
    "Renk Kodlaması Hatalı Olan İletkenlerin İşaretlenmesi ve Raporlanması",
    "Yanmaz (FR) Kablo Gerektiren Alanlarda Mevcut Durum Analizi",
    "Makine Parkuru ve Proses Revizyon Projeleri",
    "Yeni Eklenen Üretim Hatlarının Enerji İhtiyaç Analizi",
    "Taşınan Makinelerin Eski Besleme Noktalarının İptal Prosedürleri",
    "Hassas Elektronik Cihazlar İçin Harmonik ve UPS Hattı Revizyonu",
    "Makine Bazlı Enerji İzleme (Sub-metering) Altyapısı İlavesi",
    "Pnömatik ve Hidrolik Sistemlerin Elektriksel Kumanda Entegrasyonu",
    "Aydınlatma Sistemi Modernizasyonu (LED Dönüşümü)",
    "Mevcut Aydınlatma Seviyesinin (Lümen) Saha Ölçümü",
    "Konvansiyonel Armatürlerin LED Verimliliği ile Değişim Simülasyonu",
    "Acil Durum ve Kaçış Aydınlatması Fonksiyonellik Kontrolü",
    "Gün Işığına Duyarlı Sensör ve Otomasyon Revizyonları",
    "Aydınlatma Panolarının ve Zaman Saatlerinin Dijitalizasyonu",
    "Topraklama ve Eşpotansiyel Kuşaklama Revizyonu",
    "Mevcut Topraklama Ağının Süreklilik ve Direnç Ölçümü",
    "Yeni Eklenen Metal Gövdeli Makinelerin Eşpotansiyel Bağlantıları",
    "Statik Elektrik Oluşturan Prosesler İçin Özel Topraklama Çözümleri",
    "Korozyona Uğramış Topraklama İletkenlerinin Yenilenmesi",
    "Elektronik Kart Arızalarını Önlemek İçin Sinyal Topraklaması İyileştirme",
    "Yangın Algılama ve İhbar Sistemi Güncelleme",
    "Yeni Bölünen Ofis veya Depo Alanlarına Dedektör İlavesi",
    "Yangın Senaryosunun Yeni Havalandırma Sistemine Göre Revizesi",
    "Mevcut Adresli Sistemin Kapasite (Loop) Analizi",
    "Siren ve Flaşörlerin Ses/Işık Şiddeti Kapsama Alanı Kontrolü",
    "Enerji Kalitesi ve Harmonik İyileştirme",
    "Sürücülü (VFD) Motorların Sisteme Kattığı Harmoniklerin Ölçümü",
    "Aktif veya Pasif Harmonik Filtre Entegrasyon Projeleri",
    "Gerilim Dalgalanmalarına Karşı Regülasyon Revizyonları",
    "Zayıf Akım ve Network Altyapısı Yenileme",
    "Fiber Optik Omurga (Backbone) Kapasite Artırımı",
    "Saha Kamera (CCTV) Sistemine Yeni IP Noktaların Eklenmesi",
    "Personel Geçiş ve Devam Kontrol (PDKS) Donanım Revizyonu",
    "Otomasyon ve SCADA Entegrasyon Revizyonu",
    "Mevcut PLC Panolarına Giriş/Çıkış (I/O) Kart İlavesi",
    "Enerji İzleme Yazılımına Yeni Veri Noktalarının Tanımlanması",
    "Uzaktan Kontrol Senaryolarının Operasyonel Güncellemesi",
    "Jeneratör ve UPS Yedekleme Stratejisi Revizyonu",
    "Artan Yüke Göre Jeneratör Senkronizasyon Panosu İlavesi",
    "Kritik Yük Gruplarının (UPS) Yeniden Bölümlendirilmesi",
    "Otomatik Transfer Şalterlerinin (ATS) Mekanik Bakım ve Ayarları",
    "Teknik Emniyet ve İş Güvenliği (LOTO) Revizyonu",
    "Pano Önü Yalıtkan Paspas ve Uyarı Levhalarının Güncellenmesi",
    "Kilitleme/Etiketleme (Lock-Out Tag-Out) Noktalarının Belirlenmesi",
    "Ark Flaş Etiketlerinin Pano Üzerine Uygulanması",
    "Yasal Mevzuat ve Arşivleme Standartları",
    "Güncel Elektrik İç Tesisleri Yönetmeliğine Uyumluluk Denetimi",
    "Belediye ve Dağıtım Şirketi Onaylı Dosyaların Dijital Arşivlenmesi",
    "Bakım Takip Yazılımı İçin Teknik Varlık (Asset) Kodlama",
    "Metraj, Maliyet ve Uygulama Planlaması",
    "Revizyon Sırasındaki Üretim Duraksama Sürelerinin Optimizasyonu",
    "Sökülen Malzemelerin Geri Dönüşüm ve Hurda Değerlemesi",
    "Yeni Uygulama İçin Keşif Özeti ve Malzeme Onay Süreçleri",
    "Final Kabul ve \"As-Built\" Onay Süreci",
    "Sahadaki Tüm Değişikliklerin CAD Ortamına Son Aktarımı",
    "Teknik Denetim ve Fonksiyonellik Test Raporlarının Eklenmesi",
    "İşletme Bakım Personeline Revize Edilen Sistem Eğitimleri"
  ],
  "yangin-algilama-ve-ihbar-projeleri": [
    "Sistem Mimarisi ve Teknoloji Seçimi",
    "Adresli (Analogue Addressable) Sistem Tasarım Avantajları",
    "Konvansiyonel Sistemlerin Kullanım Alanları ve Sınırları",
    "Kablosuz (Wireless) Yangın Algılama Çözümleri",
    "Hibrit Sistem Yapılandırması ve Entegrasyon Kriterleri",
    "Network Edilebilir Paneller ve Merkezi İzleme Yazılımları",
    "Loop (Döngü) Sayısı ve Hat Kapasite Hesaplamaları",
    "Saha Algılama Elemanları (Dedektörler)",
    "Optik Duman Dedektörleri: Çalışma Prensibi ve Yerleşim Esasları",
    "Sıcaklık (Isı) Dedektörleri: Sabit Eşik ve Artış Hızı Duyarlılığı",
    "Kombine (Multisensör) Dedektörlerin Hatalı Alarm Önleme Kapasitesi",
    "Işın (Beam) Tipi Dedektörler: Yüksek Tavanlı Alanlarda Hizalama",
    "Aktif Hava Örneklemeli Hassas Duman Algılama Sistemleri (VESDA)",
    "Alev Dedektörleri: UV, IR ve Multi-IR Teknolojileri",
    "Kanal Tipi Duman Dedektörleri ve Havalandırma Entegrasyonu",
    "Ex-Proof (Patlamaya Dayanıklı) Dedektörlerin Tehlikeli Mahal Montajı",
    "Manuel İhbar ve Uyarı Cihazları",
    "Yangın İhbar Butonları: Yerleşim Mesafeleri ve Montaj Yüksekliği",
    "Sesli Uyarı Cihazları (Sirenler): Desibel (dB) Seviyesi Hesapları",
    "Görsel Uyarı Cihazları (Flaşörler): Görme Engelli ve Gürültülü Ortam Uyumu",
    "Sesli Anons Sistemleri (VA) ile Yangın Paneli Haberleşmesi",
    "Dış Ortam ve Endüstriyel Tip Ağır Hizmet İhbar Ekipmanları",
    "Yangın Senaryosu ve Otomasyon Kontrolü",
    "Asansör Yangın Modu: Acil Durum Katına Yönlendirme Mantığı",
    "Havalandırma ve Klima (HVAC) Sistemlerinin Durdurulması",
    "Duman Tahliye Fanlarının ve Damperlerin Aktivasyonu",
    "Elektrikli Kapı Tutucular ve Turnike Serbest Bırakma Sistemleri",
    "Gaz Kesme Valfleri ve Enerji Kesme (Trip) Modül Bağlantıları",
    "Yangın Pompası Durum İzleme ve Arıza Sinyali Takibi",
    "Kablolama ve Altyapı Standartları",
    "Yangına Dayanıklı (PH120 / FE180) Kablo Seçim Kriterleri",
    "J-H(St)H Tipi Halojensiz Yangın Kabloları ve Mekanik Koruma",
    "Loop Hattı İzolasyon Modülleri ve Kısa Devre Koruması",
    "Kablo Kanalı Doluluk Oranı ve Veri Hattı İzolasyonu",
    "Yangın Durdurucu (Fire-Stop) Mastik ve Yastık Uygulamaları",
    "Güç Gereksinimleri ve Yedekleme",
    "Yangın Paneli Akü Kapasite Hesabı (24-72 Saat Bekleme Süresi)",
    "Harici Güç Kaynakları (PSU) ve Adresli Güç Modülleri",
    "Şebeke Gerilim Dalgalanmalarına Karşı Koruma Elemanları",
    "Gaz Algılama ve Söndürme Sistemleri Kontrolü",
    "Karbonmonoksit (CO) Algılama ve Otopark Jet-Fan Entegrasyonu",
    "Doğalgaz ve LPG Kaçak Sensörleri ile Selenoid Vana Kontrolü",
    "FM200 / Novec Gazlı Söndürme Panelleri ve Manuel Başlatma",
    "Söndürme Aktif Sinyali ve Mahal Boşaltma Uyarıları",
    "Grafik İzleme ve Uzaktan Yönetim",
    "Mimari Plan Üzerinde Noktasal Arıza ve Alarm Takibi",
    "TCP/IP Üzerinden Uzaktan Panel Erişimi ve Log Kayıtları",
    "İtfaiye Tekrarlayıcı Panelleri ve Mimik Diyagramlar",
    "Mevzuat ve Standart Uyumluluğu",
    "TS EN 54 Serisi Standartların Projelendirme Sürecine Etkisi",
    "Binaların Yangından Korunması Hakkında Yönetmelik Madde Analizi",
    "Sigorta Şirketleri İçin Gerekli Yangın Güvenlik Sertifikasyonu",
    "Saha Montaj ve Uygulama Detayları",
    "Asma Tavan İçi ve Tavan Altı Dedektör Montaj Aparatları",
    "Koridor ve Merdiven Boşluğu Algılama Kriterleri",
    "Nemli ve Tozlu Alanlar İçin Koruyucu Kafes ve Muhafazalar",
    "Test, Devreye Alma ve Kabul İşlemleri",
    "Yapay Duman ve Isı Test Cihazları ile Saha Doğrulaması",
    "Sebepsiz Alarm (False Alarm) Analizi ve Hassasiyet Ayarları",
    "Yangın Senaryosu Fonksiyonellik Testleri (Matrix Testi)",
    "Bakım ve Periyodik Kontrol Prosedürleri",
    "Dedektör Kirlilik Seviyelerinin Yazılımsal Takibi",
    "3, 6 ve 12 Aylık Periyodik Bakım Formları Hazırlığı",
    "Akü Ömür Testleri ve Değişim Periyotları",
    "Teknik Çizim ve Semboloji Standartları",
    "AutoCAD Yangın Projesi Katman (Layer) Yapısı",
    "Standart Sembol Listesi (Legend) ve Kablo Şemaları",
    "Riser (Kolon) Şeması ve Loop Dağıtım Diyagramları",
    "Proje Danışmanlığı ve Resmi Onaylar",
    "Belediye ve İtfaiye Görüşü Alınması İçin Teknik Dosya",
    "Yapı Denetim Firmaları İçin Yangın Uygunluk Raporları",
    "İşletme Ruhsatı (İtfaiye Uygunluk) Süreci Yönetimi",
    "Eğitim ve İşletme Teslimi",
    "Güvenlik Personeline Yangın Paneli Kullanım Eğitimi",
    "Acil Durum Tahliye Planlarının Elektriksel Sistemle Uyumu",
    "Teknik Kataloglar ve Sertifikaların İşletmeye Teslimi"
  ],
  "proje-danismanligi": [
    "Ön Etüd ve Enerji Müsaadesi Yönetimi",
    "Dağıtım Şirketi (UEDAŞ vb.) Online Başvuru Sistemleri Kullanımı",
    "Bölge Dağıtım Şebekesi Kapasite Sorgulama ve Analizi",
    "Enerji Bağlantı Görüşü (Olumlu/Olumsuz) Teknik İncelemesi",
    "Branşman Hattı ve Bağlantı Noktası (A/B Noktası) Belirlenmesi",
    "Geçici Şantiye Enerjisi İçin Teknik Şartların Değerlendirilmesi",
    "Trafo Kurulumu Gereken Tesislerde \"Yer Tahsisi\" ve Protokolleri",
    "Belediye ve Yapı Denetim Koordinasyonu",
    "Mimari Proje Üzerinden \"Elektrik Ön Proje\" Onay Kriterleri",
    "Yapı Denetim Kuruluşları İçin Teknik Dosya ve Hesap Kontrolü",
    "Sığınak, Asansör ve Yangın Güvenlik Alanlarının Mevzuat Uyumu",
    "Isı Yalıtım ve Mekanik Projelerle Elektriksel Çakışma Analizi",
    "Kazı ve Altyapı İzinleri İçin Elektrik Rotalarının Onaylatılması",
    "Enerji Kimlik Belgesi (EKB) Veri Girişi ve Onay Takibi",
    "Dosya Hazırlama ve Teknik Dökümantasyon Standartları",
    "Resmi Onay ve Vize Süreçleri",
    "Saha Denetimi ve Kabul İşlemleri Danışmanlığı"
  ]
};

export const MAIN_SERVICES = [
  {
    id: "elektrik-uygulama-projeleri",
    title: "Elektrik Uygulama Projeleri",
    description: "Tesislerin inşaat aşamasında kullanılan, tüm detayları içeren uygulama projeleri.",
    image: "input_file_30.png"
  },
  {
    id: "elektrik-ruhsat-projeleri",
    title: "Elektrik Ruhsat Projeleri",
    description: "Belediye ve ilgili kurum onayları için hazırlanan resmi ruhsat projeleri.",
    image: "input_file_23.png"
  },
  {
    id: "elektrik-abone-projeleri",
    title: "Elektrik Abone Projeleri",
    description: "UEDAŞ ve diğer dağıtım şirketleri için abonelik işlemlerine esas teşkil eden projeler.",
    image: "input_file_8.png"
  },
  {
    id: "elektrik-guc-arttirimi-projeleri",
    title: "Elektrik Güç Arttırımı Projeleri",
    description: "Mevcut tesislerin artan enerji ihtiyacını karşılamak için hazırlanan kapasite artış projeleri.",
    image: "input_file_3.png"
  },
  {
    id: "fabrika-as-built-revizyon-projeleri",
    title: "Fabrika As-Built Revizyon Projeleri",
    description: "Fabrikaların mevcut durumunu yansıtan son hal projeleri ve revizyon çalışmaları.",
    image: "input_file_31.png"
  },
  {
    id: "yangin-algilama-ve-ihbar-projeleri",
    title: "Yangın Algılama ve İhbar Projeleri",
    description: "Yönetmeliklere uygun, can ve mal güvenliğini önceliklendiren yangın sistem projeleri.",
    image: "input_file_6.png"
  },
  {
    id: "proje-danismanligi",
    title: "Proje Danışmanlığı (UEDAŞ & Belediye)",
    description: "Bursa dışındaki firmaların Bursa'daki projeleri için yerel mevzuat ve süreç danışmanlığı.",
    image: "input_file_4.png"
  }
];

export const STRUCTURE_TYPES = [
  "Konut", "Fabrika", "İş Merkezi", "Okul", "Hastane", "Otel", "Ticaret Merkezi"
];

export const CITIES = {
  "Bursa": [
    "Osmangazi", "Nilüfer", "Yıldırım", "Gürsu", "Kestel", "Mudanya", "Gemlik", "Orhangazi", "İznik", "Mustafakemalpaşa", "Karacabey", "İnegöl", "Yenişehir", "Orhaneli", "Keles", "Büyükorhan", "Harmancık"
  ],
  "Balıkesir": [
    "Altıeylül", "Karesi", "Ayvalık", "Balya", "Bandırma", "Bigadiç", "Burhaniye", "Dursunbey", "Edremit", "Erdek", "Gömeç", "Gönen", "Havran", "İvrindi", "Marmara", "Manyas", "Savaştepe", "Sındırgı", "Susurluk"
  ],
  "Çanakkale": [
    "Merkez", "Ayvacık", "Bayramiç", "Biga", "Bozcaada", "Çan", "Eceabat", "Ezine", "Gelibolu", "Gökçeada", "Lapseki", "Yenice"
  ],
  "Yalova": [
    "Merkez", "Altınova", "Armutlu", "Çınarcık", "Çiftlikköy", "Termal"
  ]
};

export const OSB_REGIONS = [
  "Bursa OSB", "Nilüfer OSB (NOSAB)", "Demirtaş OSB (DOSAB)", "Hasanağa OSB (HOSAB)", "Kestel OSB", "Gürsu OSB", "İnegöl OSB", "Kayapa OSB", "Yenice OSB", "Mustafakemalpaşa OSB", "Karacabey OSB", "Bandırma OSB", "Gönen OSB", "Yalova Makine İhtisas OSB"
];

export const COMPANY_INFO = {
  name: "Mir Elektrik Proje Ofisi",
  tagline: "Bursa Yetkili Elektrik Firması",
  phones: ["0546 252 25 15", "0546 252 25 16"],
  whatsapp: "0546 252 25 16",
  email: "ebru@mirelektrikproje.com",
  website: "https://mirelektrikproje.com",
  address: "Doğanbey Mh Doğanbey Cd Burçin 3 İş Merkezi Kat 9 No 906 Osmangazi Bursa"
};

